// PRONO SPORT — Normalisation & déduplication des équipes (§60)
// Table d'alias entre les nomenclatures réelles des sources (football-data.co.uk ↔ TheSportsDB).
// Ce sont des correspondances de nommage, PAS des données inventées.
const ALIASES = {
  'man united': 'manchester united',
  'man utd': 'manchester united',
  'man city': 'manchester city',
  'spurs': 'tottenham hotspur',
  'tottenham': 'tottenham hotspur',
  'wolves': 'wolverhampton wanderers',
  'wolverhampton': 'wolverhampton wanderers',
  'newcastle': 'newcastle united',
  'west ham': 'west ham united',
  'west brom': 'west bromwich albion',
  'brighton': 'brighton and hove albion',
  'brighton & hove albion': 'brighton and hove albion',
  'nott m forest': 'nottingham forest',
  "nott'm forest": 'nottingham forest',
  'nottm forest': 'nottingham forest',
  'sheffield united': 'sheffield united',
  'sheffield utd': 'sheffield united',
  'leeds': 'leeds united',
  'leicester': 'leicester city',
  'luton': 'luton town',
  'ipswich': 'ipswich town',
  'ath madrid': 'atletico madrid',
  'atlético madrid': 'atletico madrid',
  'atletico de madrid': 'atletico madrid',
  'ath bilbao': 'athletic bilbao',
  'athletic club': 'athletic bilbao',
  'espanol': 'espanyol',
  'rcd espanyol': 'espanyol',
  'sociedad': 'real sociedad',
  'betis': 'real betis',
  'celta': 'celta vigo',
  'celta de vigo': 'celta vigo',
  'vallecano': 'rayo vallecano',
  'alaves': 'deportivo alaves',
  'deportivo alavés': 'deportivo alaves',
  'la coruna': 'deportivo la coruna',
  'fc barcelona': 'barcelona',
  'real madrid cf': 'real madrid',
  'sevilla fc': 'sevilla',
  'valencia cf': 'valencia',
  'villarreal cf': 'villarreal',
  'getafe cf': 'getafe',
  'girona fc': 'girona',
  'ca osasuna': 'osasuna',
  'rcd mallorca': 'mallorca',
  'elche cf': 'elche',
  'levante ud': 'levante',
  'real oviedo': 'oviedo',
  'bayern munich': 'bayern munchen',
  'bayern münchen': 'bayern munchen',
  'fc bayern münchen': 'bayern munchen',
  'fc bayern munich': 'bayern munchen',
  'dortmund': 'borussia dortmund',
  'borussia dortmund': 'borussia dortmund',
  "m'gladbach": 'borussia monchengladbach',
  'borussia mönchengladbach': 'borussia monchengladbach',
  'monchengladbach': 'borussia monchengladbach',
  'leverkusen': 'bayer leverkusen',
  'bayer 04 leverkusen': 'bayer leverkusen',
  'ein frankfurt': 'eintracht frankfurt',
  'rb leipzig': 'rb leipzig',
  'fc st pauli': 'st pauli',
  'st. pauli': 'st pauli',
  'fc koln': 'fc cologne',
  '1. fc köln': 'fc cologne',
  'koln': 'fc cologne',
  'fc heidenheim': 'heidenheim',
  '1. fc heidenheim 1846': 'heidenheim',
  'fc augsburg': 'augsburg',
  'vfb stuttgart': 'stuttgart',
  'vfl wolfsburg': 'wolfsburg',
  'sv werder bremen': 'werder bremen',
  'tsg hoffenheim': 'hoffenheim',
  'tsg 1899 hoffenheim': 'hoffenheim',
  'sc freiburg': 'freiburg',
  'fsv mainz 05': 'mainz',
  'mainz 05': 'mainz',
  '1. fsv mainz 05': 'mainz',
  'union berlin': 'union berlin',
  '1. fc union berlin': 'union berlin',
  'hamburg': 'hamburger sv',
  'inter': 'inter milan',
  'internazionale': 'inter milan',
  'fc internazionale milano': 'inter milan',
  'milan': 'ac milan',
  'juventus fc': 'juventus',
  'as roma': 'roma',
  'ss lazio': 'lazio',
  'ssc napoli': 'napoli',
  'acf fiorentina': 'fiorentina',
  'atalanta bc': 'atalanta',
  'torino fc': 'torino',
  'us cremonese': 'cremonese',
  'us sassuolo': 'sassuolo',
  'paris sg': 'paris saint-germain',
  'psg': 'paris saint-germain',
  'paris saint germain': 'paris saint-germain',
  'marseille': 'olympique marseille',
  'olympique de marseille': 'olympique marseille',
  'lyon': 'olympique lyonnais',
  'olympique lyon': 'olympique lyonnais',
  'st etienne': 'saint-etienne',
  'as saint-étienne': 'saint-etienne',
  'as monaco': 'monaco',
  'losc lille': 'lille',
  'lille osc': 'lille',
  'stade rennais': 'rennes',
  'stade rennais fc': 'rennes',
  'rc lens': 'lens',
  'ogc nice': 'nice',
  'rc strasbourg': 'strasbourg',
  'rc strasbourg alsace': 'strasbourg',
  'stade brestois 29': 'brest',
  'stade brestois': 'brest',
  'fc nantes': 'nantes',
  'toulouse fc': 'toulouse',
  'aj auxerre': 'auxerre',
  'le havre ac': 'le havre',
  'angers sco': 'angers',
  'fc metz': 'metz',
  'fc lorient': 'lorient',
  'paris fc': 'paris fc',
  'psv eindhoven': 'psv',
  'ajax amsterdam': 'ajax',
  'afc ajax': 'ajax',
  'feyenoord rotterdam': 'feyenoord',
  'az alkmaar': 'az',
  'sporting cp': 'sporting lisbon',
  'sporting lisbonne': 'sporting lisbon',
  'sp lisbon': 'sporting lisbon',
  'fc porto': 'porto',
  'sl benfica': 'benfica',
  'sc braga': 'braga',
  'sp braga': 'braga',
  'celtic fc': 'celtic',
  'rangers fc': 'rangers',
  'club brugge kv': 'club brugge',
  'fc bruges': 'club brugge',
  'royal antwerp': 'antwerp',
  'union saint-gilloise': 'st gilloise',
  'royale union saint-gilloise': 'st gilloise',
  'union sg': 'st gilloise',
  'standard liege': 'standard',
  'standard de liège': 'standard',
  'krc genk': 'genk',
  'krc gent': 'gent',
  'kaa gent': 'gent',
  'rsc anderlecht': 'anderlecht',
  'galatasaray sk': 'galatasaray',
  'fenerbahce sk': 'fenerbahce',
  'fenerbahçe': 'fenerbahce',
  'besiktas jk': 'besiktas',
  'beşiktaş': 'besiktas',
  'trabzonspor as': 'trabzonspor',
};

export function normalizeTeamName(raw) {
  if (!raw) return '';
  let s = String(raw).toLowerCase().trim()
    .normalize('NFD').replace(/[\u0300-\u036f]/g, '') // retire les accents
    .replace(/[-._]/g, ' ') // tirets/points → espaces (« Al-Hilal » ≡ « Al Hilal » entre sources)
    .replace(/\s+/g, ' ')
    .trim();
  if (NORMALIZED_ALIASES[s]) return NORMALIZED_ALIASES[s];
  // retire les préfixes/suffixes de club courants pour la mise en correspondance
  const stripped = s.replace(/^(fc|cf|ac|as|sc|sv|vfb|vfl|rc|cd|ud|us|ss|afc|ogc|krc|kaa|rsc|sk|bsc)\s+/, '')
    .replace(/\s+(fc|cf|sk|bk|if|sc)$/, '');
  if (NORMALIZED_ALIASES[stripped]) return NORMALIZED_ALIASES[stripped];
  // la forme dépouillée est la forme canonique : « Al-Nassr FC » ≡ « Al Nassr »
  return stripped || s;
}

// Les clés d'alias sont elles-mêmes normalisées (accents retirés) pour garantir
// la correspondance quel que soit l'encodage de la source.
const NORMALIZED_ALIASES = Object.fromEntries(
  Object.entries(ALIASES).map(([k, v]) => [
    k.normalize('NFD').replace(/[\u0300-\u036f]/g, ''),
    v.normalize('NFD').replace(/[\u0300-\u036f]/g, ''),
  ])
);
